language: python

python:
  - "2.7"
  - "pypy"

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}
  - tox -e $TOX_ENV --notest

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e $TOX_ENV -- pip install coveralls 
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOX_ENV=lint
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: "2.7"
      env: TOX_ENV=setup
      install: pip install tox
      script: tox -e $TOX_ENV
